### ISSUE TITLE
Unable to add more notes in mobile layout due UI bug

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerLabs/note-app-elements#9] opened 2017-04-18 07:59 UTC
Unable to add more notes in mobile layout due UI bug: notes cards are at a higher elevation than add floating action button and block up it (see attached screenshot).

![note-app-firebase-3a483 firebaseapp com](https://cloud.githubusercontent.com/assets/7892779/25120163/a6e20e86-2425-11e7-99e8-4f32a66158be.png)

**Comment by FluorescentHallucinogen** [comment] 2017-05-25 07:05
@cdata, @e111077 PTAL.

**Comment by e111077** [comment] 2017-05-25 21:34
Is this with the 2.0 version of these elements or the 1.0?

**Comment by FluorescentHallucinogen** [comment] 2017-05-26 08:04
@e111077 

I've reproduced this bug with `note-app-elements#2.0.1`.

BTW, when I install bower dependencies, I get the following error:

```
Unable to find a suitable version for webcomponentsjs, please choose one by typing one of the numbers below:
    1) webcomponentsjs#^0.7.24 which resolved to 0.7.24 and is required by polymer#1.9.1
    2) webcomponentsjs#^v1.0.0 which resolved to 1.0.1 and is required by polymer#2.0.1
```

If I answer `2`, it installs `webcomponentsjs#1.0.1`, but `polymer#1.9.1`.

**Comment by e111077** [comment] 2017-05-26 22:09
bower issue should be fixed now

**Comment by FluorescentHallucinogen** [comment] 2017-05-30 14:34
@e111077 Just tested. The problem with bower dependencies is fixed in https://github.com/PolymerLabs/note-app-elements/commit/f8e69dc97d7263eb56efb3f7ba8bffbc75e5bcbc, but the UI (CSS) bug is still here.

**Comment by e111077** [comment] 2017-05-30 21:20
I am still unable to reproduce this issue. What browser are you using? Is there any way you can get a reproduction case that I can look at? Such as a [glitch](https://glitch.com/) or a JSBin or GH repo?

**Comment by FluorescentHallucinogen** [comment] 2017-05-31 14:03
@e111077 Try https://note-app-elements-bug.firebaseapp.com in Chrome DevTools (mobile layout, width < 640px).

**Comment by FluorescentHallucinogen** [comment] 2017-05-31 14:06
> The problem with bower dependencies is fixed in https://github.com/PolymerLabs/note-app-elements/commit/f8e69dc97d7263eb56efb3f7ba8bffbc75e5bcbc

In fact, the problem with bower dependencies is completely fixed only in https://github.com/PolymerLabs/note-app-elements/pull/13.

**Comment by FluorescentHallucinogen** [comment] 2017-05-31 14:39
@e111077 Please see the following video: https://drive.google.com/open?id=0B2RP36_VaXJVeU9yNlV5YkpheDg

**Comment by FluorescentHallucinogen** [comment] 2017-06-06 10:18
@e111077 Any progress?

**Comment by e111077** [comment] 2017-06-08 00:42
This depends on #13

**Comment by e111077** [comment] 2017-06-08 21:44
The issue is that your `paper-fab` is higher in the dom than the `id="notes"` div. You should move it below. See the demo for `app-pouchdb`

**Closed as completed by e111077** 2017-06-08 21:44 UTC

**Comment by FluorescentHallucinogen** [comment] 2017-06-09 13:29
@e111077 Thanks!
